services:
  postgres:
    image: postgres:17.6
    container_name: bot-proxy-subscription-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: proxy-subscription-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/mvznfcoqe/proxy-subscription-backend:latest
    container_name: proxy-subscription-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      REMNAWAVE_PANEL_URL: ${REMNAWAVE_PANEL_URL}
      REMNAWAVE_API_KEY: ${REMNAWAVE_API_KEY}
      FREE_SQUAD_UUID: ${FREE_SQUAD_UUID}
      PAID_SQUAD_UUID: ${PAID_SQUAD_UUID}
      KEKSIK_CALLBACK_API_KEY: ${KEKSIK_CALLBACK_API_KEY}
      KEKSIK_CONFIRMATION_CODE: ${KEKSIK_CONFIRMATION_CODE}
      SUM_FOR_MONTH: ${SUM_FOR_MONTH}
      BOT_WEBHOOK_API_KEY: ${BOT_WEBHOOK_API_KEY}
      BOT_API_URL: ${BOT_API_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    image: ghcr.io/mvznfcoqe/proxy-subscription-bot:latest
    container_name: proxy-subscription-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      CHANNEL_ID: ${CHANNEL_ID}
      CHANNEL_LINK: ${CHANNEL_LINK}
      BACKEND_URL: ${BACKEND_URL}
      DONATE_BOT_USERNAME: ${DONATE_BOT_USERNAME}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      BOT_WEBHOOK_API_KEY: ${BOT_WEBHOOK_API_KEY}
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
